= Obtenga más información
:allow-uri-read: 


Es posible cambiar el certificado SSL predeterminado y la clave privada del nodo de gestión mediante la API de NetApp Element.

Cuando se configura un nodo de gestión, crea un certificado único de capa de sockets seguros (SSL) con firma automática y una clave privada que se utiliza para todas las comunicaciones HTTPS mediante la interfaz de usuario de Element, la interfaz de usuario por nodo o las API. El software Element admite certificados autofirmados, así como certificados que una entidad de certificación (CA) de confianza emite y verifica.

Puede utilizar los siguientes métodos API para obtener más información sobre el certificado SSL predeterminado y realizar cambios.

* *GetNodeSSLCertificate*
+
Puede utilizar el https://docs.netapp.com/us-en/element-software/api/reference_element_api_getnodesslcertificate.html["Método GetNodeSSLCertificate"^] Para recuperar información acerca del certificado SSL instalado actualmente, incluidos todos los detalles del certificado.

* *SetNodeSSLCertificate*
+
Puede utilizar el https://docs.netapp.com/us-en/element-software/api/reference_element_api_setnodesslcertificate.html["Método SetNodeSSLCertificate"^] Para establecer los certificados SSL por clúster y por nodo en el certificado y la clave privada que suministre. El sistema valida el certificado y la clave privada para evitar que se aplique un certificado no válido.

* *RemoveNodeSSLCertificate*
+
Este https://docs.netapp.com/us-en/element-software/api/reference_element_api_removenodesslcertificate.html["Método RemoveNodeSSLCertificate"^] Quita el certificado SSL y la clave privada instalados actualmente. A continuación, el clúster genera un nuevo certificado autofirmado y una clave privada.





== Obtenga más información

* https://docs.netapp.com/us-en/element-software/storage/reference_post_deploy_change_default_ssl_certificate.html["Cambie el certificado SSL predeterminado del software Element"^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_are_the_requirements_around_setting_custom_SSL_certificates_in_Element_Software%3F["¿Cuáles son los requisitos para configurar certificados SSL personalizados en el software Element?"^]
* https://www.netapp.com/data-storage/solidfire/documentation["Página SolidFire y Element Resources"^]
* https://docs.netapp.com/us-en/vcp/index.html["Plugin de NetApp Element para vCenter Server"^]

